1import java.util.HashMap;
2import java.util.Stack;
3
4public class Solution {
5    public int[] nextGreaterElement(int[] nums1, int[] nums2) {
6            HashMap<Integer, Integer> nextGreaterMap = new HashMap<>();
7                    Stack<Integer> stack = new Stack<>();
8                            
9                                    // Traverse nums2 from right to left
10                                            for (int i = nums2.length - 1; i >= 0; i--) {
11                                                        int num = nums2[i];
12                                                                    
13                                                                                // Pop elements from the stack until the current element is smaller
14                                                                                            while (!stack.isEmpty() && stack.peek() <= num) {
15                                                                                                            stack.pop();
16                                                                                                                        }
17                                                                                                                                    
18                                                                                                                                                // If stack is empty, no greater element to the right
19                                                                                                                                                            nextGreaterMap.put(num, stack.isEmpty() ? -1 : stack.peek());
20                                                                                                                                                                        
21                                                                                                                                                                                    // Push the current element onto the stack
22                                                                                                                                                                                                stack.push(num);
23                                                                                                                                                                                                        }
24                                                                                                                                                                                                                
25                                                                                                                                                                                                                        // Create the result array for nums1
26                                                                                                                                                                                                                                int[] result = new int[nums1.length];
27                                                                                                                                                                                                                                        for (int i = 0; i < nums1.length; i++) {
28                                                                                                                                                                                                                                                    result[i] = nextGreaterMap.get(nums1[i]);
29                                                                                                                                                                                                                                                            }
30                                                                                                                                                                                                                                                                    
31                                                                                                                                                                                                                                                                            return result;
32                                                                                                                                                                                                                                                                                }
33
34                                                                                                                                                                                                                                                                                    public static void main(String[] args) {
35                                                                                                                                                                                                                                                                                            Solution solution = new Solution();
36                                                                                                                                                                                                                                                                                                    
37                                                                                                                                                                                                                                                                                                            int[] nums1 = {4, 1, 2};
38                                                                                                                                                                                                                                                                                                                    int[] nums2 = {1, 3, 4, 2};
39                                                                                                                                                                                                                                                                                                                            int[] result = solution.nextGreaterElement(nums1, nums2);
40                                                                                                                                                                                                                                                                                                                                    
41                                                                                                                                                                                                                                                                                                                                            // Output: [-1, 3, -1]
42                                                                                                                                                                                                                                                                                                                                                    for (int res : result) {
43                                                                                                                                                                                                                                                                                                                                                                System.out.print(res + " ");
44                                                                                                                                                                                                                                                                                                                                                                        }
45                                                                                                                                                                                                                                                                                                                                                                            }
46                                                                                                                                                                                                                                                                                                                                                                            }
47                                                                                                                                                                                                                                                                                                                                                                            